version: '3.7'
services:
  swagger:
    image: swaggerapi/swagger-ui
    container_name: swagger
    ports:
      - '8080:8080'
    volumes:
      - .:/usr/share/nginx/html/doc
    environment:
      API_URL: doc/swagger.yaml